# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j6lte/setup-vendor.py

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j6lte

$(call inherit-product, vendor/samsung/j6lte/j6lte-vendor-blobs.mk)

# VINTF Manifests
DEVICE_MANIFEST_FILE += \
    vendor/samsung/j6lte/proprietary/vendor/manifest.xml \
    vendor/samsung/j6lte/proprietary/vendor/etc/vintf/manifest.xml

DEVICE_MATRIX_FILE += \
    vendor/samsung/j6lte/proprietary/vendor/etc/vintf/compatibility_matrix.xml
